const hero="/images/ChatGPT%20Image%20Sep%2030%2C%202026%2C%2003_09_03%20PM.png";

export const metadata={title:"The King's Missing Crown | Little Notebook Explorers",description:"A six-mission family adventure through Hampton Court Palace with Quill, Ziggy, Pip and Bramble."};

export default function HamptonCourt(){return <main className="adventurePage">
<header><a className="skipLink" href="#adventure-details">Skip to adventure</a><a className="brand" href="/"><span>✦</span><b>Little Notebook<br/>Explorers</b></a><nav><a href="/#adventures">Adventures</a><a href="/#books">Books</a><a href="/#how">How it works</a><a href="/#parents">For parents</a></nav><a className="button small" href="#choose">Start Exploring</a></header>

<section className="adventureHero"><div className="adventureHeroArt"><img src={hero} alt="Quill, Ziggy, Pip and Bramble ready for their Hampton Court adventure"/><a className="backPill" href="/#adventures">← All adventures</a></div><div className="adventureHeroCopy"><p className="eyebrow">HAMPTON COURT PALACE · AVAILABLE NOW</p><h1>The King’s<br/><em>Missing Crown</em></h1><p className="lead">The King’s crown has disappeared. Follow the Explorers through courtyards, kitchens and royal halls, solve the clues and recover it before it’s too late.</p><div className="adventureStats"><span><b>6</b><small>Missions</small></span><span><b>60–90</b><small>Minutes</small></span><span><b>4–8</b><small>Ages</small></span><span><b>1</b><small>Royal mystery</small></span></div><a className="button" href="#choose">Choose how to explore ↓</a></div></section>

<section id="adventure-details" className="adventureIntro"><div><p className="eyebrow">YOUR MISSION</p><h2>A palace full of clues.</h2><p>This isn’t a tour where children simply follow along. They become part of the story. Each stop reveals a new mission inspired by Hampton Court’s real history, with Quill, Ziggy, Pip and Bramble there to help.</p></div><blockquote>“Look closer. History leaves clues everywhere.”<small>— Quill</small></blockquote></section>

<section className="missionSection"><div className="sectionHeading"><p className="eyebrow">SIX MISSIONS</p><h2>From the Great Gatehouse to the missing crown.</h2><p>Each chapter unlocks at a different part of the palace, turning the visit into one connected mystery.</p></div><div className="missionGrid">
<article><i>01</i><b>Great Gatehouse</b><p>Your adventure begins. Meet the Explorers and discover the first clue.</p></article>
<article><i>02</i><b>Tudor Courtyard</b><p>Decode the Tudor Rose and match the mysterious heraldic shield.</p></article>
<article><i>03</i><b>Astronomical Clock</b><p>Use the sun, moon and Thames tide to unlock a clue hidden in time.</p></article>
<article><i>04</i><b>The Great Hall</b><p>Discover falconry, eavesdroppers and a feather that shouldn’t be there.</p></article>
<article><i>05</i><b>Tudor Kitchens</b><p>Follow a royal gingerbread recipe and uncover what the cooks know.</p></article>
<article><i>06</i><b>The Watchtower</b><p>Piece together your evidence, solve the final mystery and recover the crown.</p></article>
</div></section>

<section className="whatYouGet"><div className="notebookPanel"><span>✦</span><small>THE EXPLORER NOTEBOOK</small><b>Every clue matters.</b><p>Children collect evidence as they move through the story, use hints when they need them and build their own record of the adventure.</p></div><div><p className="eyebrow">WHAT’S INCLUDED</p><h2>Everything you need for the adventure.</h2><ul><li><b>Six interactive story missions</b><span>Built around real places inside Hampton Court.</span></li><li><b>Games, clues and discoveries</b><span>Designed to keep children looking up and exploring.</span></li><li><b>Age-friendly hints</b><span>A helping hand without giving the mystery away.</span></li><li><b>Explorer evidence & rewards</b><span>Progress that makes completing the adventure feel special.</span></li><li><b>At-home fallback</b><span>Keep playing even if part of the route is inaccessible.</span></li></ul></div></section>

<section className="familyBand"><p className="eyebrow">MADE FOR FAMILY DAYS OUT</p><h2>Less “Are we nearly done?”<br/>More “Where’s the next clue?”</h2><div><span>⌖ <b>Explore together</b><small>One family adventure, not another child disappearing into a screen.</small></span><span>✦ <b>Learn without lessons</b><small>Real Tudor history is woven naturally into the mystery.</small></span><span>♥ <b>Built for young explorers</b><small>Short missions, clear instructions and plenty to discover.</small></span></div></section>

<section id="choose" className="chooseSection"><p className="eyebrow">CHOOSE YOUR ADVENTURE</p><h2>Start with Hampton Court or unlock the whole world.</h2><div className="priceCards"><article><small>ONE-OFF ADVENTURE</small><h3>Hampton Court</h3><strong>£3.99</strong><p>Perfect if you’re visiting Hampton Court and want to try your first Little Notebook adventure.</p><ul><li>The King’s Missing Crown</li><li>All 6 missions</li><li>Family access to this adventure</li></ul><a className="button outline" href="https://app.littlenotebookexplorers.co.uk">Get Hampton Court →</a></article><article className="recommended"><span>MOST ADVENTUROUS</span><small>EXPLORER MEMBERSHIP</small><h3>Every adventure</h3><strong>£4.99 <em>/ month</em></strong><p>For families who want to keep exploring as new locations, games and discoveries arrive.</p><ul><li>Hampton Court included</li><li>Every new location</li><li>Games, profiles & Explorer Passport</li></ul><a className="button" href="https://app.littlenotebookexplorers.co.uk">Join the Adventure →</a></article></div><small className="priceNote">You’ll continue to the Little Notebook Explorers app to get started.</small></section>

<section className="beforeYouGo"><div><p className="eyebrow">BEFORE YOU GO</p><h2>A few useful things for grown-ups.</h2></div><div className="parentFaq"><details open><summary>Do we need tickets for Hampton Court Palace?</summary><p>Yes. Little Notebook Explorers is the adventure experience and does not include admission to Hampton Court Palace. Check the palace’s own opening information before travelling.</p></details><details><summary>Does my child need their own phone?</summary><p>No. The adventure is designed for a family to explore together using a grown-up’s phone.</p></details><details><summary>What if an area is closed?</summary><p>The adventure includes flexible navigation and at-home alternatives so a closure doesn’t have to end the story.</p></details><details><summary>Is it suitable for siblings?</summary><p>Yes. One family can play together, with missions designed to encourage children to look, discuss and solve clues as a team.</p></details></div></section>

<section className="nextAdventure"><p className="eyebrow">THE NOTEBOOK NEVER STAYS CLOSED FOR LONG</p><h2>Where will you explore next?</h2><p>Virginia Water and more Little Notebook adventures are on their way.</p><a className="button" href="/#adventures">See all adventures →</a></section>
<footer><div className="footerBrand"><b>Little Notebook Explorers</b><span>Big adventures start with a little notebook.</span></div><div><a href="/#adventures">Adventures</a><a href="/#books">Books</a><a href="/#parents">For parents</a></div><small>© 2026 Little Notebook Explorers</small></footer>
</main>}