const hero="/images/ChatGPT%20Image%20Sep%2030%2C%202026%2C%2003_09_03%20PM.png";

export default function Home(){return <main>
<header><a className="brand" href="#"><span>✦</span><b>Little Notebook<br/>Explorers</b></a><nav><a href="#adventures">Adventures</a><a href="#books">Books</a><a href="#how">How it works</a><a href="#parents">For parents</a></nav><a className="button small" href="#adventures">Start Exploring</a></header>

<section className="hero"><div className="copy"><p className="eyebrow">ADVENTURE IS CLOSER THAN YOU THINK</p><h1>History is hiding <em>everywhere.</em></h1><p>Join Quill, Ziggy, Pip and Bramble on magical adventures through real places, remarkable stories and the clues left behind by history.</p><div className="actions"><a className="button" href="#adventures">Start Exploring</a><a href="#adventures">See adventures →</a></div></div><div className="heroArtwork"><img src={hero} alt="Quill, Ziggy, Pip and Bramble with their explorer notebook"/><span>MEET THE EXPLORERS →</span></div></section>

<section className="trust"><div><i>⌖</i><b>Real UK locations</b><small>Adventures where history happened</small></div><div><i>▣</i><b>Interactive stories</b><small>Children become part of the adventure</small></div><div><i>✦</i><b>Games & discoveries</b><small>Look closer, solve clues, earn rewards</small></div><div><i>⌂</i><b>At home or on the go</b><small>Keep exploring wherever you are</small></div></section>

<section id="adventures" className="adventureShelf"><div className="featured"><p className="eyebrow">FEATURED ADVENTURE</p><h2>Real places. Real stories. Real fun.</h2><div className="featureCard"><div className="featureImage"><img src={hero} alt="The King's Missing Crown adventure"/><span>HAMPTON COURT PALACE</span></div><div className="featureCopy"><small>AVAILABLE NOW</small><h3>The King’s Missing Crown</h3><p>The King’s crown has disappeared! Join the Explorers on a six-mission adventure through Tudor palaces, secret passages and royal clues.</p><div className="facts"><span>♛ <b>6 missions</b></span><span>◷ <b>60–90 min</b></span><span>● <b>Ages 4–8</b></span></div><a className="button" href="#parents">Explore Hampton Court →</a><small>£3.99 individually · Included with membership</small></div></div></div><div className="coming"><p className="eyebrow">MORE ADVENTURES COMING SOON</p><div className="comingCard water"><div>🦌</div><h3>Virginia Water</h3><b>The Forest Guardian</b><span>COMING SOON</span></div><div className="comingCard forest"><div>🌲</div><h3>Alice Holt Forest</h3><b>The Hidden Trail</b><span>COMING SOON</span></div></div></section>

<section className="splitBand"><section id="how" className="howCompact"><p className="eyebrow">HOW IT WORKS</p><h2>Four steps to adventure.</h2><div className="steps"><article><i>1</i><b>Choose a location</b><p>Pick an adventure near you or at home.</p></article><article><i>2</i><b>Play the story</b><p>Follow clues and complete missions.</p></article><article><i>3</i><b>Earn your stamps</b><p>Build your Explorer Passport.</p></article><article><i>4</i><b>Unlock more</b><p>Discover new places to explore.</p></article></div></section><section className="characters"><p className="eyebrow">MEET THE EXPLORERS</p><h2>Four friends. A world of discovery.</h2><div className="characterGrid"><article><i>Q</i><b>Quill</b><p>Wise, curious and always spots the clues.</p></article><article><i>Z</i><b>Ziggy</b><p>Playful, bold and loves a good mystery.</p></article><article><i>P</i><b>Pip</b><p>Small, clever and always finds a way.</p></article><article><i>B</i><b>Bramble</b><p>Thoughtful, kind and keeps everyone on track.</p></article></div></section></section>

<section className="productRow"><article id="books" className="product books"><p className="eyebrow">DISCOVER THE BOOKS</p><h2>Stories to keep the adventure going.</h2><div className="bookcovers"><div><small>THE AMAZING HISTORY OF</small><b>TOILETS</b><span>📖</span></div><div><small>A VERY EXPLORERS</small><b>CHRISTMAS</b><span>🎄</span></div></div><a href="#books">See all books →</a></article><article className="product watch"><p className="eyebrow">WATCH & EXPLORE</p><h2>Shorts, stories and discoveries.</h2><div className="videoTile"><img src={hero} alt="Little Notebook Explorers video"/><span>▶</span></div><b>VIDEOS COMING SOON</b></article><article className="product passport"><p className="eyebrow">YOUR EXPLORER PASSPORT</p><h2>Explore. Discover. Collect.</h2><div className="passportVisual"><div><small>LITTLE NOTEBOOK</small><b>EXPLORERS</b><i>✦</i><strong>PASSPORT</strong></div><ul><li>Collect stamps from each adventure</li><li>Unlock special rewards</li><li>Build your explorer profile</li></ul></div></article></section>

<section id="parents" className="parentStrip"><div><span>✦</span><b>Why families will love it</b></div><div><b>♥ Real places, real stories</b><small>Brings history to life in a fun way.</small></div><div><b>● Quality family time</b><small>Perfect for days out or cosy days at home.</small></div><div><b>◆ Educational and fun</b><small>Builds curiosity and confidence.</small></div><div><b>★ A growing world</b><small>New locations, books and episodes.</small></div></section>

<section className="membership"><p className="eyebrow">EXPLORER MEMBERSHIP</p><h2>One membership. A world of adventures.</h2><p>Unlock every Little Notebook adventure, game and new location as they’re released.</p><strong>£4.99 <small>/ month</small></strong><a className="button" href="#adventures">Join the Adventure →</a><small>Individual adventures also available from £3.99.</small></section>

<footer><div><b>Little Notebook Explorers</b><span>Big adventures start with a little notebook.</span></div><div><a href="#adventures">Adventures</a><a href="#books">Books</a><a href="#parents">For parents</a></div><small>© 2026 Little Notebook Explorers</small></footer>
</main>}