export default function Membership(){return <main>
<header><a className="brand" href="/" aria-label="Little Notebook Explorers home"><img src="/images/lne-logo.png" alt="Little Notebook Explorers"/></a><nav><a href="/#adventures">Adventures</a><a href="/books">Books</a><a href="/#how">How it works</a><a href="/#parents">For parents</a></nav><a className="button small" href="https://app.littlenotebookexplorers.co.uk">Start Exploring</a></header>
<section className="membershipHero"><p className="eyebrow">EXPLORER MEMBERSHIP</p><h1>More adventures.<br/><em>One little membership.</em></h1><p>Choose one adventure for a special day out, or unlock the growing Little Notebook Explorers world for the whole family.</p><a className="button" href="#choose">See your options ↓</a></section>
<section className="memberBenefits"><article><span>✦</span><b>Every adventure</b><p>Explore every available location adventure as the collection grows.</p></article><article><span>⌂</span><b>At-home exploring</b><p>Keep discovering with games, stories and activities wherever you are.</p></article><article><span>♛</span><b>Explorer Passports</b><p>Children collect stamps, achievements and rewards from their adventures.</p></article><article><span>♥</span><b>Built for families</b><p>Create child profiles and keep each Explorer’s discoveries together.</p></article></section>
<section id="choose" className="membershipChoice"><div className="sectionHeading"><p className="eyebrow">CHOOSE YOUR ADVENTURE</p><h2>Start with one. Or explore them all.</h2><p>No complicated packages. Pick what works for your family.</p></div><div className="memberPriceGrid"><article><small>ONE-OFF ADVENTURE</small><h3>Just this adventure</h3><strong>£3.99</strong><p>Perfect for trying Little Notebook Explorers on a family day out.</p><ul><li>One complete location adventure</li><li>All missions and clues</li><li>Explorer Passport stamp</li><li>No subscription required</li></ul><a className="button outline" href="/adventures/hampton-court">Choose Hampton Court →</a></article><article className="memberRecommended"><span>MOST ADVENTUROUS</span><small>EXPLORER MEMBERSHIP</small><h3>The whole Explorer world</h3><strong>£4.99 <em>/ month</em></strong><p>For families who want the next adventure waiting for them.</p><ul><li>Every available location adventure</li><li>New adventures as they launch</li><li>At-home games and discoveries</li><li>Child Explorer profiles</li><li>Passport stamps and rewards</li></ul><a className="button" href="https://app.littlenotebookexplorers.co.uk">Start Exploring →</a></article></div><p className="memberFine">Membership is monthly. Cancel anytime.</p></section>
<section className="membershipWorld"><div><p className="eyebrow">WHAT YOU'RE JOINING</p><h2>A world designed to grow with your Explorers.</h2><p>Little Notebook Explorers turns real places and remarkable stories into family adventures. We’re starting close to home and adding new places, games, books and stories as the Explorer world grows.</p></div><div className="worldTiles"><article><b>🏰</b><span>Real places</span></article><article><b>🔎</b><span>Missions & clues</span></article><article><b>📖</b><span>At-home stories</span></article><article><b>⭐</b><span>Stamps & rewards</span></article></div></section>
<section className="memberFaq"><div><p className="eyebrow">FOR GROWN-UPS</p><h2>A few useful answers.</h2></div><div><details open><summary>What ages is LNE for?</summary><p>Our current adventures are designed primarily for children aged 4–8, with grown-ups joining the adventure too.</p></details><details><summary>Do I need membership?</summary><p>No. You can buy an individual adventure for £3.99. Membership is for families who want access to the growing Explorer world.</p></details><details><summary>Can siblings use it?</summary><p>Membership is designed for family use, with child profiles planned so each Explorer can build their own passport and progress.</p></details><details><summary>What happens when new adventures launch?</summary><p>Active members get access to new included adventures as they are released.</p></details><details><summary>Can I cancel?</summary><p>Yes. Membership is monthly and can be cancelled.</p></details></div></section>
<section className="memberFinal"><p className="eyebrow">READY TO EXPLORE?</p><h2>Big adventures start with a little notebook.</h2><p>Hampton Court is ready now. Virginia Water and Alice Holt Forest are coming next.</p><a className="button" href="https://app.littlenotebookexplorers.co.uk">Start Exploring →</a></section>
<footer><div className="footerBrand"><b>Little Notebook Explorers</b><span>Big adventures start with a little notebook.</span></div><div><a href="/#adventures">Adventures</a><a href="/books">Books</a><a href="/#parents">For parents</a></div><small>© 2026 Little Notebook Explorers</small></footer>
</main>}